dist: xenial
language: python
python:
  - "3.6"
services:
  - docker
env:
  - NEO4J_HOST=localhost NEO4J_PASSWORD=pword
install:
  - pip install tox neo4j-driver psycopg2
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
  - export ROBOKOP_HOME=$(pwd)/..
before_script:
  - ./tests/setup/startup_helpers.sh
script:
  - tox
after_script:
  - cd ./helpers/neo4j
  - docker-compose down
  - cd ../../tests/helpers/postgres
  - docker-compose down
  - cd ../redis
  - docker-compose down