dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_HOST=localhost NEO4J_PASSWORD=pword
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
before_script:
  - ./tests/setup_helpers.sh
script:
  - pytest --cov=messenger --cov-report term-missing
after_script:
  - codecov
  - cd neo4j
  - docker-compose down
  - cd ../postgres
  - docker-compose down
  - cd ../redis
  - docker-compose down