dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_HOST=localhost NEO4J_PASSWORD=pword
install:
  - pip install tox neo4j-driver psycopg2
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
before_script:
  - ./tests/setup_helpers.sh
script:
  - tox
after_script:
  - cd neo4j
  - docker-compose down
  - cd ../postgres
  - docker-compose down
  - cd ../redis
  - docker-compose down