dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_HOST=localhost NEO4J_PASSWORD=pword
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
before_script:
  - cd redis
  - docker-compose up -d
  - cd ..
  - cd postgres
  - docker-compose up -d
  - docker exec messenger_postgres mkdir /data
  - docker cp ./tests/data/omnicorp_mondo.csv messenger_postgres:/data/omnicorp_mondo.csv
  - docker cp ./tests/data/omnicorp_hgnc.csv messenger_postgres:/data/omnicorp_hgnc.csv
  - cd ..
  - python ./tests/init_omnicorp.py
  - cd neo4j
  - mkdir logs
  - echo "" > logs/debug.log
  - docker-compose up -d
  - until grep -q "Bolt enabled" ./neo4j/logs/debug.log; do sleep 1; done
  - cd ..
  - python ./tests/setup_neo4j.py
script:
  - pytest --cov=messenger --cov-report term-missing
after_script:
  - codecov
  - cd neo4j
  - docker-compose down
  - cd ../postgres
  - docker-compose down
  - cd ../redis
  - docker-compose down