dist: xenial
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install tox neo4j-driver psycopg2 python-dotenv
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
  - export ROBOKOP_HOME=$(pwd)/..
before_script:
  - ./tests/setup/startup_helpers.sh
script:
  - tox
after_script:
  - cd ./tests/helpers
  - docker-compose down