dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_HOST=localhost NEO4J_PASSWORD=pword
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mkdir logs
  - mkdir cache
  - export PYTHONPATH=$(pwd)
before_script:
  - cd neo4j
  - mkdir logs
  - echo "" > logs/debug.log
  - docker-compose up -d
  - cd ..
  - until grep -q "Bolt enabled" ./neo4j/logs/debug.log; do sleep 1; done
  - python ./tests/setup_neo4j.py
script:
  - pytest --cov=messenger --cov-report term-missing
after_script:
  - codecov
  - cd neo4j
  - docker-compose down