dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_HOST=robokopdb2.renci.org NEO4J_PASSWORD=blahb
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mkdir logs
  - mkdir cache
before_script:
  - cd neo4j
  - mkdir logs
  - echo "" > logs/debug.log
  - docker-compose up -d
  - cd ..
  - until grep -q "Bolt enabled" ./neo4j/logs/debug.log
    do
        sleep 1
    done
script:
  - PYTHONPATH=. pytest --cov=messenger --cov-report term-missing
after_script:
  - codecov
  - cd graph
  - docker-compose down