version: "3"
services:
  messenger:
    container_name: messenger
    build:
      context: .
    command: 'gunicorn --bind 0.0.0.0:4868 -w 4 -k gevent -t 600 main:app'
    user: "${UID}:${GID}"
    env_file:
      - ../shared/robokop.env
    environment:
      - ROBOKOP_HOME=/home/murphy
      - PYTHONPATH=/home/murphy/robokop-messenger
    ports:
      - "${MESSENGER_PORT}:${MESSENGER_PORT}"
    volumes:
      - ../logs:/home/murphy/logs
      - ../shared:/home/murphy/shared
      - ./:/home/murphy/robokop-messenger
