version: "3"
services:
  neo4j:
    image: neo4j:3.5.4
    container_name: messenger_neo4j
    environment:
      - NEO4J_AUTH=neo4j/pword
    volumes:
      - ./logs:/logs
    ports:
      - 7474:7474
      - 7687:7687