openapi: 3.0.2
info:
  title: {{ title|default('<title>') }}
  description: {{ description|default('\<description\>') }}
  version: {{ version|default('<version>') }}
  contact:
    email: {{ email|default('<email>') }}
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  x-reasoner_standard_version: 0.9.2
tags:
  - name: reasoner
  - name: translator
{% if path is defined -%}
servers:
  - url: "/{{ path }}"
{% endif -%}
paths:
  {%- for endpoint in endpoints %}
  /{{ endpoint.operation }}:
    post:
      tags:
        - reasoner
      summary: {{ endpoint.description.split('\n')[0]|default('<summary>')}}
      description: ''
      operationId: {{ endpoint.operation|default('not_implemented') }}
      requestBody:
        description: Request
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  $ref: '#/components/schemas/Message'
                options:
                  type: object
                  {%- if endpoint.parameters|length %}
                  properties:
                    {%- for parameter in endpoint.parameters %}
                    {{ parameter.name }}:
                      type: {{ parameter.type }}
                      example: {{ parameter.default }}
                      default: {{ parameter.default }}
                    {%- endfor %}
                  {%- endif %}
              required:
                - message
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              example:
                  results:
                    - n00: ['MONDO:0005737']
                  query_graph:
                    nodes:
                      - id: n00
                        curie: MONDO:0005737
                    edges: []
                  knowledge_graph:
                    nodes:
                      - id: MONDO:0005737
                    edges: []
        '400':
          description: Invalid input
      x-openapi-router-controller: controllers
  {%- endfor %}
{% include 'components.yaml' %}